apiVersion: apps/v1
kind: Deployment
metadata: 
  name: circleci-flux  
  labels: 
    name: "circleci-flux"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: circleci-flux
  template:
    metadata:
      name: circleci-flux
      labels:
        app: circleci-flux
    spec:     
      containers:                    
        - image: suraj18/circlecci-flux:v1.0.0 
          imagePullPolicy: Always # this is required to force pull image     
          name: circleci-flux
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: circleci-flux
spec:
  selector:
    app: circleci-flux
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

